src/Entity/Disponibilite.php
<?php

namespace App\Entity;

use App\Repository\DisponibiliteRepository;
use Doctrine\DBAL\Types\Types;
use Symfony\Component\Validator\Constraints as Assert;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: DisponibiliteRepository::class)]
class Disponibilite
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(type: Types::DATE_MUTABLE)]
    #[Assert\NotBlank(message: "Veuillez renseigner une date de début.")]
    #[Assert\type("DateTime", message: "Veuillez entrer une date de début dans un format valide exemple: 01/06/2024")]
    #[Assert\LessThan(propertyPath:"date_fin", message:"La date de début doit être antèrieure a la date de fin.")]
    #[Assert\GreaterThan("today", message:"La date de début doit être ultèrieure a aujourd'hui.")]
    private ?\DateTimeInterface $date_debut = null;

    #[ORM\Column(type: Types::DATE_MUTABLE)]
    #[Assert\NotBlank(message: "Veuillez renseigner une date de fin")]
    #[Assert\Type("DateTime", message: "Veuillez entrer une date de fin dans un format valide exemple: 01/06/2024")]
    #[Assert\GreaterThan(propertyPath:"date_debut", message:"La date de fin doit être ultèrieure a la date de début.")]
    private ?\DateTimeInterface $date_fin = null;

    #[ORM\Column]
    #[Assert\NotBlank(message: "Veuillez renseigner un prix de de location par jour.")]
    #[Assert\Positive(message: "Le prix doit être supérieur a 0.")]
    private ?int $prix_jour = null;

    #[ORM\Column]
    private ?bool $statut = null;

    #[ORM\ManyToOne(inversedBy: 'disponibilite')]
    private ?Vehicule $vehicule = null;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getDateDebut(): ?\DateTimeInterface
    {
        return $this->date_debut;
    }

    public function setDateDebut(\DateTimeInterface $date_debut): static
    {
        $this->date_debut = $date_debut;

        return $this;
    }

    public function getDateFin(): ?\DateTimeInterface
    {
        return $this->date_fin;
    }

    public function setDateFin(\DateTimeInterface $date_fin): static
    {
        $this->date_fin = $date_fin;

        return $this;
    }

    public function getPrixJour(): ?int
    {
        return $this->prix_jour;
    }

    public function setPrixJour(int $prix_jour): static
    {
        $this->prix_jour = $prix_jour;

        return $this;
    }

    public function isStatut(): ?bool
    {
        return $this->statut;
    }

    public function setStatut(bool $statut): static
    {
        $this->statut = $statut;

        return $this;
    }

    public function getVehicule(): ?Vehicule
    {
        return $this->vehicule;
    }

    public function setVehicule(?Vehicule $vehicule): static
    {
        $this->vehicule = $vehicule;

        return $this;
    }
}

templates/index/_form.html.twig
{% form_theme searchForm 'partials/_customForm.html.twig' %}

{{ form_start(searchForm) }}
    {{ form_row(searchForm.date_debut) }}
	{{ form_row(searchForm.date_fin) }}
	{{ form_row(searchForm.prix_max) }}
	<button type='submit' class="px-3 py-2 mt-10 text-sm font-semibold text-white bg-green-600 rounded-md shadow-sm hover:bg-green-500 focus-visible:outline focus-visible:outline-2 focus-visible:outline-offset-2 focus-visible:outline-green-600">{{button_label|default('Rechercher')}}</button>
{{ form_end(searchForm) }}

templates/index/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Bienvenue
{% endblock %}

{% block body %}
	<div class="bg-van-sunset h-[calc(100vh_-_80px)] bg-cover bg-bottom relative">
		<div class="absolute bottom-1/4 left-1/2 translate-x-[-50%] w-1/2 backdrop-blur-sm text-black py-10 rounded-xl">
			<div class="w-3/4 mx-auto">
				<div class="w-3/4 mx-auto">
				<h1 class="mb-8 text-4xl font-bold">Trouver un camping-car à louer</h1>
					{% include "index/_form.html.twig" %}
				</div>
			</div>
		</div>
	</div>
{% endblock %}

templates/index/results.html.twig
{% extends 'base.html.twig' %}

{% block title %}Bienvenue
{% endblock %}

{% block body %}
    <h1 class="w-4/5 py-8 text-4xl font-black uppercase ">Liste des disponibilités</h1>
	 <div class="flex flex-wrap w-4/5 px-4 mx-auto">
	{% if disponibilites %}
		{% for disponibilite in disponibilites %}
		<div class="max-w-sm overflow-hidden rounded shadow-lg">
			<img class="w-full" src="/logos/van-placeholder.png" alt="Sunset in the mountains">
			<div class="px-6 py-4">
				<div class="mb-2 text-xl font-bold">{{disponibilite.vehicule.marque}} {{disponibilite.vehicule.modele}}</div>
                <div class="flex flex-col">
                    <time datetime="{{disponibilite.dateDebut|date('d/m/Y')}}"><span class="font-bold">Date de début:</span> {{disponibilite.dateDebut|date('d/m/Y')}}</time>
				    <time datetime="{{disponibilite.dateFin|date('d/m/Y')}}"><span class="font-bold">Date de fin:</span> {{disponibilite.dateFin|date('d/m/Y')}}</time>
					<div><span class="font-bold">Prix par jour :</span> {{disponibilite.prixJour}} €</div>
                </div>
            </div>
			<div class="flex flex-row gap-3 px-6 pt-4 pb-2">
                <a href="#">
					<button type="button" class="block px-3 py-2 text-sm font-semibold text-center text-white bg-green-700 rounded-md shadow-sm hover:bg-th-orange-hover focus-visible:outline focus-visible:outline-2 focus-visible:outline-offset-2 focus-visible:outline-indigo-600">Réserver</button>
				</a>
			</div>
		</div>
	{% endfor %}
	{% else %}
	<h1>Aucun Résultats pour votre recherche</h1>
	{% endif %}
	    </div>


{% endblock %}